import { useState } from "react";
import MapButton from "./MapButton";

function MapCells() {
  return (
    <>
      <table>
        <tr>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
        </tr>
        <tr>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
        </tr>
        <tr>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
        </tr>
        <tr>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
        </tr>
        <tr>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
        </tr>
        <tr>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
        </tr>
        <tr>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
        </tr>
        <tr>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
        </tr>
        <tr>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
        </tr>
        <tr>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
        </tr>
        <tr>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
        </tr>
        <tr>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
        </tr>
        <tr>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
          <th>
            <MapButton>.</MapButton>
          </th>
        </tr>
      </table>
    </>
  )
}

export default MapCells;